USE fpdata

DELETE FROM tmpPlayedTracks WITH (ROWLOCK)
DELETE FROM PlayedTracks WITH (ROWLOCK)
TRUNCATE TABLE Fingerprints
TRUNCATE TABLE SubFingerprints
DELETE FROM Tracks WITH (ROWLOCK)
DELETE FROM Albums WITH (ROWLOCK)
DELETE FROM Artists WITH (ROWLOCK)
DELETE FROM Genres WITH (ROWLOCK)

DBCC CHECKIDENT('tmpPlayedTracks', RESEED, 0)
DBCC CHECKIDENT('PlayedTracks', RESEED, 0)
DBCC CHECKIDENT('Fingerprints', RESEED, 0)
DBCC CHECKIDENT('SubFingerprints', RESEED, 0)
DBCC CHECKIDENT('Tracks', RESEED, 0)
DBCC CHECKIDENT('Albums', RESEED, 0)
DBCC CHECKIDENT('Artists', RESEED, 0)
DBCC CHECKIDENT('Genres', RESEED, 0)

DBCC SHRINKDATABASE ('fpData')
